services:
  - type: web
    name: vocaliq-backend
    env: docker
    rootDir: backend # Ensure this is correct (if your app.py and Dockerfile are in 'backend/')
    dockerfilePath: ./Dockerfile # Path relative to rootDir
    dockerCommand: uvicorn app:app --host 0.0.0.0 --port ${PORT}
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: PORT # Render will use this $PORT in the dockerCommand
        value: 10000 # The port your app will listen on
      - key: CUDA_VISIBLE_DEVICES
        value: "0"  # Use first GPU if available
    disk:
      name: audio-storage
      mountPath: /app/static
      sizeGB: 1
    buildFilter:
      paths:
        - backend/**
    buildCache:
      enabled: true
    # Add GPU configuration if your deployment platform supports it
    gpu:
      type: nvidia-tesla-t4  # or whatever GPU type is available
      count: 1